version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    # user: vscode

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspaces/wgkex:cached
      # Add cache mounts for pip and Docker images, which are pulled in entrypoint.sh
      - pip-cache:/root/.cache/pip
      - docker-cache:/var/lib/docker

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  mqtt:
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - .devcontainer/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - .devcontainer/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro # user: broker, password: SECRET

volumes:
  pip-cache:
  docker-cache:
