name: Sync .bazelversion with Dockerfile

on:
  pull_request:

jobs:
  update-bazelversion:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Extract Bazel version from Dockerfile
        id: extract_version
        run: |
          version=$(grep -oP '(?<=gcr.io/bazel-public/bazel:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "bazel_version=$version" >> $GITHUB_OUTPUT

      - name: Update .bazelversion if different
        run: |
          current_version=$(cat .bazelversion | tr -d '[:space:]')
          if [ "$current_version" != "${{ steps.extract_version.outputs.bazel_version }}" ]; then
            echo "${{ steps.extract_version.outputs.bazel_version }}" > .bazelversion
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .bazelversion
            git commit -m "chore: sync .bazelversion with Dockerfile"
            git push origin ${{ github.head_ref }}
          else
            echo ".bazelversion is already up to date."
          fi
