name: Sync .bazelversion with Dockerfile

on:
  pull_request:

jobs:
  update-bazelversion:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Extract Bazel version from Dockerfile
        id: extract_version
        run: |
          version=$(grep -oP '(?<=gcr.io/bazel-public/bazel:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "bazel_version=$version" >> $GITHUB_OUTPUT
      
      - name: Update .bazelversion if different
        run: |
          new_version="${{ steps.extract_version.outputs.bazel_version }}"
          current_version=$(cat .bazelversion | tr -d '[:space:]')
      
          if [ "$current_version" != "$new_version" ]; then
            printf "%s\n# make sure that the image in the Dockerfile and this version are identical\n" "$new_version" > .bazelversion
      
            # Commit only if there are real changes
            if ! git diff --quiet; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add .bazelversion
              git commit -m "chore: sync .bazelversion with Dockerfile"
              git push origin ${{ github.head_ref }}
            else
              echo "No changes detected after update."
            fi
          else
            echo ".bazelversion is already up to date."
          fi
